# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informacion_exportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_mercancia', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peso_kilogramos', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigo_arancelario', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('numero_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exportapp.mes')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exportapp.tipo_producto'),
        ),
        migrations.AddField(
            model_name='informacion_exportacion',
            name='codigo_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exportapp.pais'),
        ),
        migrations.AddField(
            model_name='informacion_exportacion',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exportapp.producto'),
        ),
        migrations.AddField(
            model_name='informacion_exportacion',
            name='codigo_temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exportapp.temporada'),
        ),
    ]
