# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.IntegerField()),
            ],
        ),
    ]
